### ISSUE TITLE
Run pytest-sort without running tests?

### ISSUE THREAD

**Issue by tomviner** [moccu/pytest-isort#1]
I'd like to run pytest-isort in a separate section of my tox.ini file, like I have linting in a separate section.

I've tried `py.test --isort --collect-only` or ways to deselect tests, but these all end up preventing the isort from running.

Is there a way of doing this?

**Comment by stephrdev** [comment]
collect-only just collects possible test jobs and won't execute any tests. pytest-isort works just like pytest-pep8 and pytest-flakes. You could mark your "real" tests with pytest.mark and then deselect these tests when executing your "lint only" CI job.

Do you see any other option to do so? I'm not sure if we yould add a marker to all IsortItems to have them selected easily. What do you think?

**Comment by asvetlov** [comment]
I believe it can be closed as "want fix"

**Comment by tomviner** [comment]
I agree: "won't fix".

I think you're doing this in the standard way. And using marks you can indeed select either a) just isort (with `--isort -m "isort"`), b) everything but isort (with `-m "not isort"` or just don't add `--isort`).

**Comment by ifischer** [comment]
I managed to configure pytest-isort via conftest.py to run isort checks without running tests :
```python 
# conftest.py

def pytest_collection_modifyitems(session, config, items):
    if config.getoption('--isort'):
        items[:] = [item for item in items if item.get_marker('isort')]
```
Works for pytest-flake8 the same way.
