### ISSUE TITLE
Settings not read from [isort] section in setup.cfg

### ISSUE THREAD

**Issue by tiktuk** [moccu/pytest-isort#13]
Could be really nice if config was read from `[isort]` section so `pytest-isort` read the same settings as `isort`on the command line.

**Comment by tiktuk** [comment]
Oh, it's because it's looking for `setup.cfg` next to the test file which in my case is in a subfolder. I wonder if it could be made to look for `setup.cfg` from where `pytest`was run.

**Comment by stephrdev** [comment]
Interesting bit. Personally, I use editorconfig to configure isort. Does this problem still exist? If yes, we should try to fix that.

**Comment by cb109** [comment]
I can confirm the `isort.cfg` from project root was ignored. I could workaround by adding a section to my `tox.ini` which was parsed as expected.

**Comment by stephrdev** [comment]
I double checked the docs, the config should be named ".isort.cfg" (leading dot) - does it work then?

**Comment by cb109** [comment]
@stephrdev Thank you for taking the time to look into that. You are correct, my bad, `.isort.cfg` is read as expected :+1:
