### ISSUE TITLE
Fix PytestDeprecationWarning

### ISSUE THREAD

**Issue by impredicative** [moccu/pytest-isort#19]
Thank you for this invaluable package. Lately I see this message:

```
venv/lib/python3.8/site-packages/pytest_isort.py:43: PytestDeprecationWarning: direct construction of IsortItem has been deprecated, please use IsortItem.from_parent
    return IsortItem(path, parent)
```

Please see this [**similar issue with comments**](https://github.com/carsongee/pytest-pylint/issues/120) providing additional info.

**Comment by stephrdev** [comment]
Fixed with new release 1.0.0
