### ISSUE TITLE
Silently skip already checked files

### ISSUE THREAD

**Issue by asvetlov** [moccu/pytest-isort#2]
Now the plugin skips file if timestamp is not changed after previous run.

That's perfectly fine but it marks the test as 'skipped', see
https://github.com/moccu/pytest-isort/blob/master/pytest_isort.py#L145

It confuses me because a number of skipped tests in report varies from run to run.

I suggest keep skipping but without reporting about it.

Please mark *cached* file as passed.

**Comment by asvetlov** [comment]
Hi. Is the project alive?
If you are ok with proposed change I might make a Pull Request.
If you want to keep existing functionality by default I might add extra command line parameter and config file option to enable the change only on user demand.
What I definitely don't want to do is forking your really cool project and publishing it under another name on PyPI.

**Comment by stephrdev** [comment]
Hi!
Yes - the project is still active. I just missed your request in the first place.
I think marking the files as skipped is common practice (pytest-pep8 and pytes-flakes work the same way) and should be kept.

I'm not sure if adding an option for it is the best way as add options alway also brings the burden of maintaining it.

**Comment by asvetlov** [comment]
Ok, thanks for explanation
