### ISSUE TITLE
isort no longer uses isort.SortImports in recent versions

### ISSUE THREAD

**Issue by mattBoros** [moccu/pytest-isort#25]
In recent versions of isort, the isort.SortImports function has been removed. Since the setup.py file in this repo allows for any version of isort above 4.0, I get an attribute error on SortImports when running pytest-isort. This isn't shown in isorts [latest documentation](https://isort.readthedocs.io/en/stable/), but a quick `pip3 install isort` and `from isort import SortImports` shows the error.

**Comment by bnavigator** [comment]
Already accounted for by #24.
