### ISSUE TITLE
Add option to pass -m -l parameter to make it possible to run with pytest-black

### ISSUE THREAD

**Issue by d21d3q** [moccu/pytest-isort#28]
Since bare (with default options) `isort` is not compatible with `black` code formatter, however [it is possible](https://copdips.com/2020/04/making-isort-compatible-with-black.html) to make it compatible by sorting with mode `-m 3 -l 88`. 

Suggestion: add option to config file:
```
[isort]
mode = 3
line_length = 88
```
so that it can be run with 
```
pytest --black --isort
```

**Comment by stephrdev** [comment]
You can use whatever option isort provides. I personally use the .editorconfig way but any other way that isort provides will work as we simply call the isort linter.
