### ISSUE TITLE
support for custom line length

### ISSUE THREAD

**Issue by samuelcolvin** [moccu/pytest-isort#3]
would be great if pytest-isort could support isort's `-w` line length option.

Preferable in `setup.cfg/pytest.ini`.

Maybe this is already possible? But not documented.

**Comment by stephrdev** [comment]
You can use .isort.cfg oder .editorconfig (https://github.com/timothycrosley/isort#configuring-isort). These files will be loaded by isort.

**Comment by samuelcolvin** [comment]
Great, thanks a lot, works well.
