### ISSUE TITLE
Missing option for profile 

### ISSUE THREAD

**Issue by Wurstnase** [moccu/pytest-isort#32]
isort can be configured into a "black"-mode.

--profile black

It would be nice, when we had the same for this plugin. Something like the ignore-filter.
e.g.:
```
isort_profile = black
```

**Comment by stephrdev** [comment]
pytest-isort / isort still reads the default configurations. You can simply put "profile = black" to your editorconfig for example or any other config file listed here: https://pycqa.github.io/isort/docs/configuration/config_files/

**Comment by Wurstnase** [comment]
Awesome. Thanks, also for the direct link.
