### ISSUE TITLE
Trailing commas in import lists

### ISSUE THREAD

**Issue by khink** [moccu/pytest-isort#5]
This is valid:
```
import (
    x,
    y
)
````
This is not:
```
import (
    x,
    y,
)
````
I can't find if this is a standard. 

For keeping diffs cleaner, it would be nice to accept trailing commas, or making it configurable.

**Comment by stephrdev** [comment]
Please refer to isort's configuration for issues like this. pytest-isort is just a wrapper for isort.
https://github.com/timothycrosley/isort#configuring-isort
